export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_SCHEMA_HOST = "SET_SCHEMA_HOST";
export const SET_SCHEMA_PORT = "SET_SCHEMA_PORT";

export const STORE_FORM_DATA = "STORE_FORM_DATA";
export const STORE_COMMENTARIES = "STORE_COMMENTARIES";
export const STORE_PORTFOLIOS = "STORE_PORTFOLIOS";
export const STORE_POSITIONS = "STORE_POSITIONS";
export const STORE_BARS = "STORE_BARS";
export const STORE_ORDERS = "STORE_ORDERS";
export const STORE_SIGNALS = "STORE_SIGNALS";
export const STORE_ANALYTICS = "STORE_ANALYTICS";
